# Generated by Django 5.1.4 on 2025-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='submitted_cvs',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='employee.cv'),
        ),
    ]
