# Generated by Django 5.1.4 on 2025-01-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_cv_attachment_cv_characteristics_cv_civil_status_and_more'),
        ('employer', '0002_jobpost_submitted_cvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(help_text='Date the job was offered')),
                ('acceptance_date', models.DateField(blank=True, help_text='Date the offer was accepted', null=True)),
                ('start_date', models.DateField(help_text='Official start date of employment')),
                ('end_date', models.DateField(blank=True, help_text='Planned end date for fixed-term contracts', null=True)),
                ('termination_date', models.DateField(blank=True, help_text='Actual termination date if agreement ended early', null=True)),
                ('modification_date', models.DateField(blank=True, help_text='Date of last agreement modification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='employer.employer')),
            ],
            options={
                'verbose_name': 'Job Agreement',
                'verbose_name_plural': 'Job Agreements',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='employer_jo_start_d_fe6a5b_idx'), models.Index(fields=['end_date'], name='employer_jo_end_dat_fd2ded_idx')],
            },
        ),
    ]
