# Generated by Django 5.1.4 on 2025-01-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_jobagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobagreement',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='employer.jobpost'),
        ),
        migrations.AddField(
            model_name='jobagreement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='pending', help_text='Current status of the job agreement', max_length=20),
        ),
    ]
