# Generated by Django 5.1.4 on 2025-01-31 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_jobagreement_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
        migrations.AddField(
            model_name='employer',
            name='contact_name',
            field=models.CharField(default='Zigmas', max_length=255, verbose_name='Kontaktinis asmuo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Sukurta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktyvus'),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(default=455224, max_length=20, verbose_name='Telefono numeris'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atnaujinta'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Įmonės pavadinimas'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='El. paštas'),
        ),
    ]
