# Generated by Django 5.1.4 on 2025-01-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_employer_options_employer_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
