# Generated by Django 5.1.4 on 2025-01-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_employer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_logos/'),
        ),
    ]
