# Generated by Django 5.1.4 on 2025-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='employee_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to the employee', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='employer_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount employer pays for the assignment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='manager_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Commission earned by the manager', max_digits=10, null=True),
        ),
    ]
