# Generated by Django 5.1.4 on 2025-02-21 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='business_days',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Faktiškai išdirbtos darbo dienos', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='business_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Faktiškai išdirbtos darbo valandos', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Darbuotojo dienos tarifas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employee_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Darbuotojo valandinis tarifas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employer_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Darbdavio dienos tarifas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employer_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Darbdavio valandinis tarifas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Menedžerio komisinių procentas (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Faktiškai išdirbtos dienos', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Faktiškai išdirbtos valandos', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
