# Generated by Django 5.1.4 on 2025-02-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_jobapplication_cv_applications'),
        ('employer', '0012_employer_has_agreement'),
        ('eor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.cv'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.jobpost'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
