# Generated by Django 5.1.4 on 2025-02-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_customuser_groups_and_more'),
        ('employer', '0001_initial'),
        ('eor', '0002_alter_employeeassignment_employee_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_tariff_type', models.CharField(choices=[('hourly', 'Už valandą'), ('daily', 'Už dieną')], default='hourly', max_length=10)),
                ('employee_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Darbuotojo valandinis tarifas', max_digits=10, null=True)),
                ('employee_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Darbuotojo dienos tarifas', max_digits=10, null=True)),
                ('employer_tariff_type', models.CharField(choices=[('hourly', 'Už valandą'), ('daily', 'Už dieną')], default='hourly', max_length=10)),
                ('employer_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Darbdavio valandinis tarifas', max_digits=10, null=True)),
                ('employer_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Darbdavio dienos tarifas', max_digits=10, null=True)),
                ('manager_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Menedžerio komisinių procentas', max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_employee', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_employer', to='employer.employer')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_manager', to='eor.manager')),
            ],
        ),
    ]
