# Generated by Django 5.1.4 on 2025-02-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_customuser_groups_and_more'),
        ('employer', '0001_initial'),
        ('eor', '0007_alter_contract_employee_alter_contract_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_employee', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_employer', to='employer.employer'),
        ),
    ]
