# Generated by Django 5.1.4 on 2025-02-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.jobpost'),
        ),
        migrations.AddField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employee.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarday',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('employee', 'job_post')},
        ),
    ]
