# Generated by Django 5.1.4 on 2025-01-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
