# Generated by Django 5.1.4 on 2025-01-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_calendar_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='cv_attachments/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='cv',
            name='characteristics',
            field=models.TextField(default='geras', verbose_name='CHARACTERISTICS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='civil_status',
            field=models.CharField(default='vedes', max_length=255, verbose_name='CIVIL STATUS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='contacts',
            field=models.CharField(default='zirniu g', max_length=255, verbose_name='CONTACTS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='date_and_place_of_birth',
            field=models.CharField(default='Vilnius', max_length=255, verbose_name='DATE AND PLACE OF BIRTH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='hobby',
            field=models.TextField(default='Saskes', verbose_name='HOBBY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='languages',
            field=models.TextField(default='lenku, rusu', verbose_name='LANGUAGES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='name_surname',
            field=models.CharField(default='Zebrauskas', max_length=255, verbose_name='NAME, SURNAME'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='other_relevant_information',
            field=models.TextField(default='jokios', verbose_name='OTHER RELEVANT INFORMATION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='place_of_residence',
            field=models.CharField(default='Ziezmariai', max_length=255, verbose_name='PLACE OF RESIDENCE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='professional_experience',
            field=models.TextField(default='Jokios', verbose_name='PROFESSIONAL EXPERIENCE'),
            preserve_default=False,
        ),
    ]
