# Generated by Django 5.1.4 on 2025-01-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_cv_attachment_cv_characteristics_cv_civil_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
