# Generated by Django 5.1.4 on 2025-02-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_is_email_verified'),
        ('employer', '0010_remove_jobpost_submitted_cvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.cv')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employee.employee')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.jobpost')),
            ],
            options={
                'unique_together': {('employee', 'job_post')},
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='applications',
            field=models.ManyToManyField(blank=True, through='employee.JobApplication', to='employer.jobpost'),
        ),
    ]
