# Generated by Django 5.1.4 on 2025-02-10 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_jobapplication_cv_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('mokejimo_tipas', models.CharField(choices=[('alga', 'Alga'), ('avansinis', 'Avansinis'), ('atskaitymas', 'Atskaitymas')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
