# Generated by Django 5.1.4 on 2025-02-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employee_payments_documents/', verbose_name='Document'),
        ),
    ]
